FROM ruby:3.1.3 AS rails-env

WORKDIR /app
COPY api .

RUN apt-get update && apt-get install -y \
    imagemagick libmagickwand-dev --no-install-recommends \
    && pecl install imagick \
    && docker-php-ext-enable imagick

RUN gem install rails bundler
RUN bundle install

ENTRYPOINT ["bundle", "exec"]
